baseURL = 'https://frogzone.neocities.org/'
languageCode = 'en-us'
title = 'frogzone'
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
MetaDataFormat = "toml"
uglyURLs = true
summaryLength = 10

[params]
site-creation-date = 2025-12-20

[security]
enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[indexes]
    category = "categories"
    tag = "tags"

[author]
    name = "willy"

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'

[build]
writeStats = true

[build.processing.css]
enable = true
filetype = "scss"


[menus]
[[menus.main]]
name = 'home'
pageRef = '/'
weight = -1

[[menus.main]]
name = 'blog'
pageRef = '/blog/'
weight = 10

[[menus.main]]
name = 'music'
pageRef = '/music/'
weight = 20

[[menus.main]]
name = 'writing'
pageRef = '/writing/'
weight = 21

[[menus.main]]
name = 'food'
pageRef = '/food/'
weight = 22

[[menus.main]]
name = 'links'
pageRef = '/links/'
weight = 30

[[menus.main]]
name = 'about'
pageRef = '/about/'
weight = 31

[[menus.main]]
name = "travelogue"
pageRef = '/travelogue/'
weight = 11

[[menus.main]]
name = 'guestbook'
pageRef = '/guestbook/'
weight = 32