baseURL = 'https://frogzone.neocities.org/'
languageCode = 'en-us'
title = 'frogzone'
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
MetaDataFormat = "toml"
uglyURLs = true

[indexes]
    category = "categories"
    tag = "tags"
[author]
    name = "willy dowden"

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'

[build]
writeStats = true
[build.processing.css]
enable = true
filetype = "scss"


[menus]
[[menus.main]]
name = 'home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'blog'
pageRef = '/blog/'
weight = 3

[[menus.main]]
name = 'music'
pageRef = '/music/'
weight = 4

[[menus.main]]
name = 'writing'
pageRef = '/writing/'
weight = 6

[[menus.main]]
name = 'links'
pageRef = '/links/'
weight = 5

[[menus.main]]
name = 'about'
pageRef = '/about/'
weight = 2

[[menus.main]]
name = 'contact'
pageRef = '/contact/'
weight = 7